# -*- coding: utf-8 -*-
"""lab3-soln.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i9NPJ79atrgDxPDRe4NE1ZxYyDdg6X4n

# **Statistical Language Modeling and Sequence Analysis**

# Task 1 — Brown Corpus & N-gram **Analysis**

Cell 1: Imports and **Downloads**
"""

import nltk
import pandas as pd
import math
import re

from collections import Counter
from nltk.corpus import brown
from nltk.tokenize import word_tokenize
from nltk.util import ngrams

nltk.download('brown')
nltk.download('punkt')
nltk.download('punkt_tab')

"""Cell 2: Load Brown News **Corpus**"""

# Load Brown Corpus - News category
news_words = brown.words(categories='news')

# Select at least 5000 tokens
news_words = news_words[:5000]

# Basic preprocessing
cleaned_words = [
    word.lower()
    for word in news_words
    if word.isalpha()
]

print("Total Tokens:", len(cleaned_words))
print("Vocabulary Size:", len(set(cleaned_words)))

"""Cell 3: Generate Unigram, Bigram and **Trigram**"""

# Generate N-grams

unigrams = list(ngrams(cleaned_words, 1))
bigrams = list(ngrams(cleaned_words, 2))
trigrams = list(ngrams(cleaned_words, 3))

# Frequency counts

unigram_freq = Counter(unigrams)
bigram_freq = Counter(bigrams)
trigram_freq = Counter(trigrams)

"""Cell 4: Top 10 **Unigrams**"""

top_unigrams = unigram_freq.most_common(10)

unigram_df = pd.DataFrame(
    top_unigrams,
    columns=["Unigram", "Frequency"]
)

unigram_df

"""Cell 5: Top 10 **Bigrams**"""

top_bigrams = bigram_freq.most_common(10)

bigram_df = pd.DataFrame(
    top_bigrams,
    columns=["Bigram", "Frequency"]
)

bigram_df

"""Cell 6: Top 10 **Trigrams**"""

top_trigrams = trigram_freq.most_common(10)

trigram_df = pd.DataFrame(
    top_trigrams,
    columns=["Trigram", "Frequency"]
)

trigram_df

"""# **Task 2 — Bigram Language Model**

Cell 1: Load Gutenberg **Corpus**
"""

nltk.download('gutenberg')

from nltk.corpus import gutenberg

# Load English text
emma_words = gutenberg.words('austen-emma.txt')

# Select a portion of the corpus
emma_words = emma_words[:10000]

# Tokenize and normalize
cleaned_emma = [
    word.lower()
    for word in emma_words
    if word.isalpha()
]

print("Total Tokens:", len(cleaned_emma))
print("Vocabulary Size:", len(set(cleaned_emma)))

"""Cell 2: Unigram and Bigram **Counts**"""

# Unigram frequency
unigram_counts = Counter(cleaned_emma)

# Bigram frequency
bigram_counts = Counter(
    ngrams(cleaned_emma, 2)
)

# Vocabulary size
V = len(unigram_counts)

print("Number of Unigrams:", len(unigram_counts))
print("Number of Bigrams:", len(bigram_counts))

"""Cell 3: Add-One **Smoothing**"""

def bigram_probability(previous_word, current_word):

    bigram_count = bigram_counts[
        (previous_word, current_word)
    ]

    previous_count = unigram_counts[
        previous_word
    ]

    probability = (
        (bigram_count + 1)
        / (previous_count + V)
    )

    return probability

"""Cell 4: Sentence **Score**"""

def sentence_score(sentence):

    words = [
        word.lower()
        for word in word_tokenize(sentence)
        if word.isalpha()
    ]

    score = 0

    for i in range(1, len(words)):

        probability = bigram_probability(
            words[i-1],
            words[i]
        )

        score += math.log(probability)

    return score

"""Cell 5: Test 3 **Sentences**"""

test_sentences = [
    "The woman was happy",
    "The man went home",
    "She reads a good book"
]

for sentence in test_sentences:

    score = sentence_score(sentence)

    print("Sentence:", sentence)
    print("Score:", score)
    print()

"""# **Task 4 — Ambiguity, Coreference & Domain Language**

Part A — **Ambiguity**
"""

ambiguity_data = [

    ["bank",
     "I deposited money in the bank.",
     "Financial institution"],

    ["bank",
     "We sat on the bank of the river.",
     "Side of a river"],

    ["bat",
     "The player hit the ball with a bat.",
     "Sports equipment"],

    ["bat",
     "A bat was flying in the night.",
     "Animal"],

    ["light",
     "Please turn on the light.",
     "Illumination"],

    ["light",
     "This bag is very light.",
     "Not heavy"],

    ["match",
     "India won the cricket match.",
     "Sports game"],

    ["match",
     "She used a match to light the candle.",
     "Small stick used for fire"],

    ["plant",
     "The plant needs water.",
     "Living organism"],

    ["plant",
     "The workers operate the plant.",
     "Industrial facility"]
]

ambiguity_df = pd.DataFrame(
    ambiguity_data,
    columns=[
        "Word",
        "Sentence",
        "Intended Meaning"
    ]
)

ambiguity_df

"""Part B — **Coreference**"""

coreference_data = [

    ["Riya went to college. She attended her NLP class.",
     "She",
     "Riya"],

    ["The dog was hungry. It ate the food.",
     "It",
     "The dog"],

    ["Rahul bought a laptop. He uses it every day.",
     "He",
     "Rahul"],

    ["The students completed the assignment. They submitted it.",
     "They",
     "The students"],

    ["Anjali opened her notebook. She started writing.",
     "She",
     "Anjali"]
]

coreference_df = pd.DataFrame(
    coreference_data,
    columns=[
        "Sentence",
        "Pronoun",
        "Antecedent"
    ]
)

coreference_df

"""# Part C — 20 **Newsgroups**

Cell **1**
"""

from sklearn.datasets import fetch_20newsgroups

"""Cell **2**"""

# Select two domains

categories = [
    "sci.space",
    "comp.graphics"
]

# Load dataset

newsgroups_data = fetch_20newsgroups(
    subset='train',
    categories=categories,
    remove=('headers', 'footers', 'quotes')
)

print("Number of Documents:", len(newsgroups_data.data))

"""Cell 3: Extract Domain **Terms**"""

# Combine all documents

all_text = " ".join(
    newsgroups_data.data
)

# Convert to lowercase
# Extract words

words_list = re.findall(
    r'\b[a-zA-Z]{3,}\b',
    all_text.lower()
)

print("Total Words Extracted:", len(words_list))

"""Cell 4: Remove **Stopwords**"""

nltk.download('stopwords')

from nltk.corpus import stopwords

stop_words = set(
    stopwords.words('english')
)

filtered_words = [
    word
    for word in words_list
    if word not in stop_words
]

"""Cell 5: Top 20 Domain **Terms**"""

word_frequency = Counter(
    filtered_words
)

top_20_terms = word_frequency.most_common(20)

domain_df = pd.DataFrame(
    top_20_terms,
    columns=[
        "Domain Term",
        "Frequency"
    ]
)

domain_df

"""# **Conclusion**

This lab helped us understand N-gram analysis, Bigram Language Models, ambiguity, coreference, and domain-specific language using NLP datasets. We also learned how context helps in understanding the meaning of words and sentences.
"""